# Generated by Django 3.2.4 on 2022-02-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='days',
            name='content',
            field=models.TextField(blank=True, verbose_name='Особливості проведення'),
        ),
        migrations.AlterField(
            model_name='days',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата та час проведеня дійства'),
        ),
        migrations.AlterField(
            model_name='days',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Упубліковано'),
        ),
        migrations.AlterField(
            model_name='days',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва дійства'),
        ),
        migrations.AddField(
            model_name='days',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='life.category_days', verbose_name='Категорія дня'),
        ),
    ]
